version: '3'

services: 
    website:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8000:5000 
        volumes: 
            - .:/app
        depends_on: 
            - db
    
    db:
        image: mysql:5.7.22
        restart: always
        environment: 
            MYSQL_DATABASE: messageApp
            # MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 33066:3306

    